package render

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/cagedbird043/fcm-hosts-next/internal/pipeline"
)

type Meta struct {
	SeedV4 int
	SeedV6 int
	SelV4  int
	SelV6  int
	Now    time.Time
}

func WriteAll(dir string, r pipeline.Result) error {
	m := Meta{SeedV4: r.SeedV4, SeedV6: r.SeedV6, SelV4: len(r.SelectedV4), SelV6: len(r.SelectedV6), Now: time.Now().UTC()}
	if len(r.SelectedV4) > 0 {
		if err := write(filepath.Join(dir, "fcm_ipv4.hosts"), content(assign(r.SelectedV4, false), "IPv4 Only", m)); err != nil {
			return err
		}
	}
	if len(r.SelectedV6) > 0 {
		if err := write(filepath.Join(dir, "fcm_ipv6.hosts"), content(assign(r.SelectedV6, false), "IPv6 Only", m)); err != nil {
			return err
		}
	}
	dualEntries := [][2]string{}
	if len(r.SelectedV4) > 0 && len(r.SelectedV6) > 0 {
		for i, d := range pipeline.FCMDomains {
			dualEntries = append(dualEntries, [2]string{r.SelectedV4[i%len(r.SelectedV4)], d})
			dualEntries = append(dualEntries, [2]string{r.SelectedV6[i%len(r.SelectedV6)], d})
		}
		return write(filepath.Join(dir, "fcm_dual.hosts"), content(dualEntries, "Dual Stack (IPv4 + IPv6)", m))
	}
	if len(r.SelectedV4) > 0 {
		dualEntries = assign(r.SelectedV4, false)
		return write(filepath.Join(dir, "fcm_dual.hosts"), content(dualEntries, "Dual Stack (IPv4 Only)", m))
	}
	if len(r.SelectedV6) > 0 {
		dualEntries = assign(r.SelectedV6, false)
		return write(filepath.Join(dir, "fcm_dual.hosts"), content(dualEntries, "Dual Stack (IPv6 Only)", m))
	}
	return fmt.Errorf("no selected FCM IPs")
}

func assign(ips []string, _ bool) [][2]string {
	out := make([][2]string, 0, len(pipeline.FCMDomains))
	for i, d := range pipeline.FCMDomains {
		out = append(out, [2]string{ips[i%len(ips)], d})
	}
	return out
}

func content(entries [][2]string, typ string, m Meta) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by Project Mjolnir\n")
	fmt.Fprintf(&b, "# Date: %s\n", m.Now.Format("2006-01-02 15:04:05 MST"))
	fmt.Fprintf(&b, "# Type: %s\n", typ)
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "# FCM Domains: %s...\n", strings.Join(pipeline.FCMDomains[:3], ", "))
	fmt.Fprintf(&b, "# Generated using Go single-node TCP 5228 ranking with nearby expansion\n")
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "# Seeds: IPv4=%d, IPv6=%d\n", m.SeedV4, m.SeedV6)
	fmt.Fprintf(&b, "# Selected: IPv4=%d, IPv6=%d\n", m.SelV4, m.SelV6)
	if v := os.Getenv("GITHUB_RUN_ID"); v != "" {
		fmt.Fprintf(&b, "# Workflow Run: %s\n", v)
	}
	if v := os.Getenv("GITHUB_SHA"); v != "" {
		if len(v) > 12 {
			v = v[:12]
		}
		fmt.Fprintf(&b, "# Commit: %s\n", v)
	}
	if v := os.Getenv("RUNNER_NAME"); v != "" {
		fmt.Fprintf(&b, "# Verified On: %s\n", v)
	}
	b.WriteString("\n")
	seen := map[[2]string]bool{}
	for _, e := range entries {
		if e[0] == "" || e[1] == "" {
			continue
		}
		if seen[e] {
			continue
		}
		seen[e] = true
		fmt.Fprintf(&b, "%s %s\n", e[0], e[1])
	}
	return b.String()
}

func write(path, s string) error { return os.WriteFile(path, []byte(s), 0644) }
